from enum import StrEnum


class ResultCode(StrEnum):
    # Success
    SUCCESS = "SUCCESS"
    CREATED = "CREATED"
    UPDATED = "UPDATED"
    DELETED = "DELETED"

    # Client Error
    INVALID_PARAM = "INVALID_PARAM"
    MISSING_PARAM = "MISSING_PARAM"
    DUPLICATE_RESOURCE = "DUPLICATE_RESOURCE"
    RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND"
    UNAUTHORIZED = "UNAUTHORIZED"
    FORBIDDEN = "FORBIDDEN"

    # Business Error
    BUSINESS_ERROR = "BUSINESS_ERROR"
    USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS"

    # Server Error
    INTERNAL_ERROR = "INTERNAL_ERROR"
    DATABASE_ERROR = "DATABASE_ERROR"